name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download ngrok v3
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract ngrok
        run: Expand-Archive ngrok.zip -DestinationPath ngrok

      - name: Auth
        run: .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start simple HTTP server
        run: |
          echo "<h1>Server is running</h1>" > index.html
          python -m http.server 8080 &
          Start-Sleep -Seconds 5

      - name: Create HTTP tunnel
        run: .\ngrok\ngrok.exe http 8080
